name: ahmetozkanio
description: Portfolio website for Ahmet Özkan.

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.8.0

  google_fonts: ^4.0.4
  get: ^4.6.5
  get_storage: ^2.1.1
  flutter_native_splash: ^2.2.19
  http: ^0.13.5
  url_launcher: ^6.1.6
  sticky_headers: ^0.3.0+2
  flutter_markdown: ^0.6.14
  
  flutter_svg: ^1.1.5

  google_nav_bar: ^5.0.6
  auto_size_text: ^3.0.0

  delayed_display: ^2.0.0

  syncfusion_flutter_pdfviewer: ^20.3.52
  blur: ^3.1.0
  animations: ^2.0.7
  # Firebase
  # firebase_core: ^3.4.0
  # firebase_crashlytics: ^4.1.0
  # firebase_analytics: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/splash/ahmetozkanio_light.png
  color: "F9FAEF"
  image_dark: assets/splash/ahmetozkanio_dark.png
  color_dark: "12140E" 
  web: true
  android: false
  ios: false
  fullscreen: true 


flutter:

  uses-material-design: true

  # assets:
    # - assets/logo/